name: Docker Image CI  

on:  
  push:  
    branches: [ main, ui/* ]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/os-checker:latest
  IMAGE_TAR: /tmp/os-checker.tar

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v4  
      
    # Create and boot a builder using by default the docker-container driver.
    # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=${{ env.IMAGE_TAR }}

    - name: Load and Run Docker image
      run: |
        docker load --input ${{ env.IMAGE_TAR }}
        docker image ls -a
        # DEBUG means compiling os-checker from source
        docker run -e DEBUG=1 -v /check:/check ${{ env.IMAGE }}

    # - name: Display the result of os-checker 
    #   run: cat /check/summary.txt >> $GITHUB_STEP_SUMMARY

    - name: Upload pages artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: /check/dist/

    - name: Commit and push test.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "zjp-CN"
        git config user.email "jiping_zhou@foxmail.com"
        git config committer.name "zjp-CN[bot]"
        git config committer.email "zjp-CN[bot]@users.noreply.github.com"
        # echo "The head commit message is: ${{ github.event.head_commit.message }}" > commit.txt
        # git add commit.txt
        cp /check/test.json os-checks/content/test.json
        git add os-checks/content/test.json
        git commit -m "[bot] update os-checks/content/test.json"
        git push 

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
